collections:
  - name: "faq_general"
    label: "General FAQs"
    folder: "content/faqs/general"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "text" }

  - name: "faq_investments"
    label: "Investments FAQs"
    folder: "content/faqs/investments"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "text" }

  - name: "faq_security"
    label: "Security & Safety FAQs"
    folder: "content/faqs/security"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "text" }
