backend:
  name: github
  repo: curiousfire/mahaana-knowledge-base
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "faqs"
    label: "FAQ Items"
    folder: "content/faqs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Account Information", "Investments", "Deposits and Withdrawals", "Fees", "Shariah Compliance", "General"]}
      - {label: "Order", name: "order", widget: "number", default: 100}
      - {label: "Body", name: "body", widget: "markdown"}
