backend:
  name: git-gateway
  branch: main

site_url: https://loquacious-blancmange-d6f58d.netlify.app

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: general_faqs
    label: "General FAQs"
    folder: "content/faqs/general"
    create: true
    slug: "{{slug}}"
    identifier_field: "question"
    fields:
      - label: "Question"
        name: "question"
        widget: "string"
      - label: "Answer"
        name: "answer"
        widget: "text"

  - name: account_faqs
    label: "Account & Verification FAQs"
    folder: "content/faqs/account"
    create: true
    slug: "{{slug}}"
    identifier_field: "question"
    fields:
      - label: "Question"
        name: "question"
        widget: "string"
      - label: "Answer"
        name: "answer"
        widget: "text"

  - name: investments_faqs
    label: "Investments & Funds FAQs"
    folder: "content/faqs/investments"
    create: true
    slug: "{{slug}}"
    identifier_field: "question"
    fields:
      - label: "Question"
        name: "question"
        widget: "string"
      - label: "Answer"
        name: "answer"
        widget: "text"
