backend:
  name: git-gateway
  branch: main

site_url: https://loquacious-blancmange-d6f58d.netlify.app

media_folder: "static/img"
public_folder: "/img"

collections:
  # Only dynamic collections will be shown here after the build process
  
  # New collection to manage FAQ categories
  - name: faq_collections
    label: "FAQ Categories"
    folder: "content/faq_collections"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - label: "Category Name"
        name: "name"
        widget: "string"
        hint: "Name of the FAQ category (e.g., 'Payments', 'Security')"
      - label: "Folder Name"
        name: "folder"
        widget: "string"
        hint: "Folder name for this category (lowercase, no spaces, e.g., 'payments')"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
